var BRICK_LIST = [
    { name: "tile_1x1", stackable: false, isPublic: true },
    { name: "tile_2x1", stackable: false, isPublic: true },
    { name: "tile_3x1", stackable: false, isPublic: true },
    { name: "tile_4x1", stackable: false, isPublic: true },
    { name: "tile_6x1", stackable: false, isPublic: true },
    { name: "tile_8x1", stackable: false, isPublic: true },
    { name: "tile_10x1", stackable: false, isPublic: true },
    { name: "tile_16x1", stackable: false, isPublic: true },

    { name: "tile_2x2", stackable: false, isPublic: true },
    { name: "tile_3x2", stackable: false, isPublic: true },
    { name: "tile_4x2", stackable: false, isPublic: true },
    { name: "tile_6x2", stackable: false, isPublic: true },
    { name: "tile_8x2", stackable: false, isPublic: true },
    { name: "tile_10x2", stackable: false, isPublic: true },
    { name: "tile_16x2", stackable: false, isPublic: true },

    { name: "tile_3x3", stackable: false, isPublic: true },
    { name: "tile_4x4", stackable: false, isPublic: true },
    { name: "tile_6x6", stackable: false, isPublic: true },
    { name: "tile_8x8", stackable: false, isPublic: true },
    { name: "tile_10x10", stackable: false, isPublic: true },
    { name: "tile_16x16", stackable: false, isPublic: true },

    { name: "brick_1x1", stackable: true, isPublic: true },
    { name: "brick_2x1", stackable: true, isPublic: true },
    { name: "brick_3x1", stackable: true, isPublic: true },
    { name: "brick_4x1", stackable: true, isPublic: true },
    { name: "brick_6x1", stackable: true, isPublic: true },
    { name: "brick_8x1", stackable: true, isPublic: true },
    { name: "brick_10x1", stackable: true, isPublic: true },
    { name: "brick_16x1", stackable: true, isPublic: true },

    { name: "brick-corner-round_1x1", stackable: false, isPublic: true },
    { name: "brick-round_1x1", stackable: false, isPublic: true },
    { name: "brick-round_2x1", stackable: false, isPublic: true },
    { name: "brick-round_3x1", stackable: false, isPublic: true },
    { name: "brick-round_4x1", stackable: false, isPublic: true },
    { name: "brick-round_6x1", stackable: false, isPublic: true },
    { name: "brick-round_8x1", stackable: false, isPublic: true },
    { name: "brick-round_10x1", stackable: false, isPublic: true },
    { name: "brick-round_16x1", stackable: false, isPublic: true },
    
    { name: "tile-corner-curved_2x1", stackable: false, isPublic: true },
    { name: "tile-corner-curved_3x1", stackable: false, isPublic: true },
    { name: "tile-corner-curved_4x1", stackable: false, isPublic: true },
    { name: "tile-corner-curved_5x1", stackable: false, isPublic: true },
    { name: "tile-corner-curved_6x1", stackable: false, isPublic: true },
    { name: "tile-corner-curved_7x1", stackable: false, isPublic: true },
    { name: "tile-corner-curved_8x1", stackable: false, isPublic: true },
    
    { name: "tile-corner-curved_3x2", stackable: false, isPublic: true },
    { name: "tile-corner-curved_4x2", stackable: false, isPublic: true },
    { name: "tile-corner-curved_5x2", stackable: false, isPublic: true },
    { name: "tile-corner-curved_6x2", stackable: false, isPublic: true },
    { name: "tile-corner-curved_7x2", stackable: false, isPublic: true },
    { name: "tile-corner-curved_8x2", stackable: false, isPublic: true },
    
    { name: "brick-corner-curved_2x1", stackable: false, isPublic: true },
    { name: "brick-corner-curved_3x1", stackable: false, isPublic: true },
    { name: "brick-corner-curved_4x1", stackable: false, isPublic: true },
    { name: "brick-corner-curved_5x1", stackable: false, isPublic: true },
    { name: "brick-corner-curved_6x1", stackable: false, isPublic: true },
    { name: "brick-corner-curved_7x1", stackable: false, isPublic: true },
    { name: "brick-corner-curved_8x1", stackable: false, isPublic: true },

    { name: "window-frame_2x2", stackable: false, isPublic: true },
    { name: "window-frame_2x3", stackable: false, isPublic: true },
    { name: "window-frame_2x4", stackable: false, isPublic: true },
    { name: "window-frame_2x6", stackable: false, isPublic: true },
    { name: "window-frame_3x2", stackable: false, isPublic: true },
    { name: "window-frame_3x3", stackable: false, isPublic: true },
    { name: "window-frame_3x4", stackable: false, isPublic: true },
    { name: "window-frame_3x6", stackable: false, isPublic: true },
    { name: "window-frame_4x2", stackable: false, isPublic: true },
    { name: "window-frame_4x3", stackable: false, isPublic: true },
    { name: "window-frame_4x4", stackable: false, isPublic: true },
    { name: "window-frame_4x6", stackable: false, isPublic: true },

    { name: "window-frame-corner-curved_3x2", stackable: false, isPublic: true },
    { name: "window-frame-corner-curved_3x3", stackable: false, isPublic: true },
    { name: "window-frame-corner-curved_3x4", stackable: false, isPublic: true },
    { name: "window-frame-corner-curved_3x6", stackable: false, isPublic: true },

    { name: "plate-quarter_1x1", stackable: false, isPublic: true },
    { name: "plate-quarter_2x2", stackable: false, isPublic: true },
    { name: "plate-quarter_3x3", stackable: false, isPublic: true },
    { name: "plate-quarter_4x4", stackable: false, isPublic: true },
    { name: "plate-quarter_5x5", stackable: false, isPublic: true },
    { name: "plate-quarter_6x6", stackable: false, isPublic: true },
    { name: "plate-quarter_7x7", stackable: false, isPublic: true },
    { name: "plate-quarter_8x8", stackable: false, isPublic: true },

    { name: "brick-quarter_1x1", stackable: false, isPublic: true },
    { name: "brick-quarter_2x2", stackable: false, isPublic: true },
    { name: "brick-quarter_3x3", stackable: false, isPublic: true },
    { name: "brick-quarter_4x4", stackable: false, isPublic: true },
    { name: "brick-quarter_5x5", stackable: false, isPublic: true },
    { name: "brick-quarter_6x6", stackable: false, isPublic: true },
    { name: "brick-quarter_7x7", stackable: false, isPublic: true },
    { name: "brick-quarter_8x8", stackable: false, isPublic: true },

    { name: "wall_1x1", stackable: true, isPublic: true },
    { name: "wall_2x1", stackable: true, isPublic: true },
    { name: "wall_3x1", stackable: true, isPublic: true },
    { name: "wall_4x1", stackable: true, isPublic: true },
    { name: "wall_6x1", stackable: true, isPublic: true },
    { name: "wall_8x1", stackable: true, isPublic: true },
    { name: "wall_10x1", stackable: true, isPublic: true },
    { name: "wall_16x1", stackable: true, isPublic: true },

    { name: "text_8_DODOPOLIS", stackable: true, isPublic: false },
    { name: "text_10_BRICKS & BLOCKS", stackable: true, isPublic: false },
    { name: "text_10_PAINT & PIGMENTS", stackable: true , isPublic: false},
    { name: "text_8_PLAYGROUND", stackable: true, isPublic: false },

    { name: "stairs_1x1", stackable: false, isPublic: true },
    { name: "stairs_2x1", stackable: false, isPublic: true },
    { name: "stairs_3x1", stackable: false, isPublic: true },
    { name: "stairs_4x1", stackable: false, isPublic: true },
    { name: "stairs_6x1", stackable: false, isPublic: true },
    { name: "stairs_8x1", stackable: false, isPublic: true },
    { name: "stairs_10x1", stackable: false, isPublic: true },
    { name: "stairs_16x1", stackable: false, isPublic: true },

    { name: "text_8_TIARATUM", stackable: true, isPublic: false },
    { name: "text_6_GAMES", stackable: true, isPublic: false },

    { name: "picture_marble-run-simulator", stackable: true, isPublic: false, src: "./datas/textures/marble-run-simulator.png" },
    { name: "picture_carillion", stackable: true, isPublic: false, src: "./datas/textures/carillion.png" },
    
    { name: "arcade_dodoqix", stackable: true, isPublic: false }
]